In [1]:
print("British Airways Lounge Eligibility")

British Airways Lounge Eligibility

In [3]:
import pandas

df=pandas.read_excel("British Airways Summer Schedule Dataset - Forage Data Science Task 1.xlsx")

In [4]:
df.shape

(10000, 17)

In [5]:
df.head(3)

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40

In [6]:
df.columns

Index(['FLIGHT_DATE', 'FLIGHT_TIME', 'TIME_OF_DAY', 'AIRLINE_CD', 'FLIGHT_NO',
       'DEPARTURE_STATION_CD', 'ARRIVAL_STATION_CD', 'ARRIVAL_COUNTRY',
       'ARRIVAL_REGION', 'HAUL', 'AIRCRAFT_TYPE', 'FIRST_CLASS_SEATS',
       'BUSINESS_CLASS_SEATS', 'ECONOMY_SEATS', 'TIER1_ELIGIBLE_PAX',
       'TIER2_ELIGIBLE_PAX', 'TIER3_ELIGIBLE_PAX'],
      dtype='str')

In [9]:
for clm in df.columns:
    print(f"{clm} : {df[clm].value_counts()}\n--------------------------------")

FLIGHT_DATE : FLIGHT_DATE
2025-06-05    68
2025-08-16    68
2025-06-15    66
2025-04-25    66
2025-05-02    65
              ..
2025-10-19    33
2025-04-19    32
2025-05-09    31
2025-10-18    30
2025-05-03    29
Name: count, Length: 210, dtype: int64
--------------------------------
FLIGHT_TIME : FLIGHT_TIME
16:49:00    20
17:24:00    20
10:42:00    19
20:23:00    19
09:48:00    19
            ..
07:21:00     2
14:08:00     2
15:56:00     2
11:24:00     2
22:49:00     1
Name: count, Length: 1020, dtype: int64
--------------------------------
TIME_OF_DAY : TIME_OF_DAY
Morning      3530
Evening      2973
Afternoon    2305
Lunchtime    1192
Name: count, dtype: int64
--------------------------------
AIRLINE_CD : AIRLINE_CD
BA    10000
Name: count, dtype: int64
--------------------------------
FLIGHT_NO : FLIGHT_NO
BA8347    7
BA5934    7
BA5015    6
BA7761    6
BA6477    6
         ..
BA9029    1
BA2627    1
BA1631    1
BA9712    1
BA8374    1
Name: count, Length: 6037, dtype: int64
--------------------------------
DEPARTURE_STATION_CD : DEPARTURE_STATION_CD
LHR    10000
Name: count, dtype: int64
--------------------------------
ARRIVAL_STATION_CD : ARRIVAL_STATION_CD
FRA    714
MUC    691
DXB    688
VIE    682
HND    679
ORD    675
MAD    673
LAX    666
JFK    664
DFW    653
IST    650
BCN    645
AMS    641
CDG    641
ZRH    638
Name: count, dtype: int64
--------------------------------
ARRIVAL_COUNTRY : ARRIVAL_COUNTRY
USA            2658
Germany        1405
Spain          1318
UAE             688
Austria         682
Japan           679
Turkey          650
Netherlands     641
France          641
Switzerland     638
Name: count, dtype: int64
--------------------------------
ARRIVAL_REGION : ARRIVAL_REGION
Europe           5975
North America    2658
Middle East       688
Asia              679
Name: count, dtype: int64
--------------------------------
HAUL : HAUL
SHORT    5975
LONG     4025
Name: count, dtype: int64
--------------------------------
AIRCRAFT_TYPE : AIRCRAFT_TYPE
A320    5975
B777    1878
B787    1236
A350     535
A380     376
Name: count, dtype: int64
--------------------------------
FIRST_CLASS_SEATS : FIRST_CLASS_SEATS
0     8348
8     1276
14     376
Name: count, dtype: int64
--------------------------------
BUSINESS_CLASS_SEATS : BUSINESS_CLASS_SEATS
32    936
48    648
49    632
56    535
97    376
12    334
42    306
31    304
13    299
18    297
9     297
1     296
2     295
3     294
15    289
35    288
20    285
4     285
19    283
11    281
17    280
14    279
5     276
8     270
7     269
0     269
16    267
10    265
6     265
Name: count, dtype: int64
--------------------------------
ECONOMY_SEATS : ECONOMY_SEATS
178    927
300    617
166    585
179    584
173    573
275    535
358    376
200    338
168    334
304    319
224    310
167    299
162    297
171    297
177    294
165    289
160    285
176    285
161    283
169    281
163    280
175    276
172    270
180    269
164    267
170    265
174    265
Name: count, dtype: int64
--------------------------------
TIER1_ELIGIBLE_PAX : TIER1_ELIGIBLE_PAX
0     6232
1     2345
2      887
3      328
4      122
5       58
6       19
7        4
8        2
9        2
20       1
Name: count, dtype: int64
--------------------------------
TIER2_ELIGIBLE_PAX : TIER2_ELIGIBLE_PAX
0     944
9     723
8     721
7     720
6     690
10    686
5     636
11    601
4     566
12    539
3     490
2     444
13    435
14    398
1     315
15    295
16    238
17    185
18    118
19     96
20     60
21     34
22     27
23     16
25     10
24      8
29      2
26      2
27      1
Name: count, dtype: int64
--------------------------------
TIER3_ELIGIBLE_PAX : TIER3_ELIGIBLE_PAX
0     290
27    273
33    264
30    259
29    259
     ...
90      1
92      1
81      1
85      1
83      1
Name: count, Length: 86, dtype: int64
--------------------------------

In [10]:
for clm in df.columns:
    print(f"{clm} : {df[clm].unique()}\n-------------------------------")

FLIGHT_DATE : <DatetimeArray>
['2025-09-02 00:00:00', '2025-06-10 00:00:00', '2025-10-27 00:00:00',
 '2025-06-15 00:00:00', '2025-08-25 00:00:00', '2025-07-12 00:00:00',
 '2025-09-16 00:00:00', '2025-04-24 00:00:00', '2025-05-17 00:00:00',
 '2025-05-01 00:00:00',
 ...
 '2025-07-10 00:00:00', '2025-07-23 00:00:00', '2025-04-19 00:00:00',
 '2025-08-26 00:00:00', '2025-10-07 00:00:00', '2025-09-18 00:00:00',
 '2025-09-24 00:00:00', '2025-06-09 00:00:00', '2025-08-07 00:00:00',
 '2025-10-23 00:00:00']
Length: 210, dtype: datetime64[us]
-------------------------------
FLIGHT_TIME : [datetime.time(14, 19) datetime.time(6, 42) datetime.time(15, 33) ...
 datetime.time(17, 38) datetime.time(11, 52) datetime.time(11, 24)]
-------------------------------
TIME_OF_DAY : <StringArray>
['Afternoon', 'Morning', 'Evening', 'Lunchtime']
Length: 4, dtype: str
-------------------------------
AIRLINE_CD : <StringArray>
['BA']
Length: 1, dtype: str
-------------------------------
FLIGHT_NO : <StringArray>
['BA5211', 'BA7282', 'BA1896', 'BA5497', 'BA1493', 'BA4954', 'BA9840',
 'BA7116', 'BA4424', 'BA4878',
 ...
 'BA6948', 'BA1385', 'BA7380', 'BA7896', 'BA6196', 'BA9029', 'BA2627',
 'BA1631', 'BA9712', 'BA8374']
Length: 6037, dtype: str
-------------------------------
DEPARTURE_STATION_CD : <StringArray>
['LHR']
Length: 1, dtype: str
-------------------------------
ARRIVAL_STATION_CD : <StringArray>
['LAX', 'FRA', 'IST', 'VIE', 'AMS', 'ORD', 'MUC', 'HND', 'CDG', 'ZRH', 'JFK',
 'MAD', 'DXB', 'BCN', 'DFW']
Length: 15, dtype: str
-------------------------------
ARRIVAL_COUNTRY : <StringArray>
[        'USA',     'Germany',      'Turkey',     'Austria', 'Netherlands',
       'Japan',      'France', 'Switzerland',       'Spain',         'UAE']
Length: 10, dtype: str
-------------------------------
ARRIVAL_REGION : <StringArray>
['North America', 'Europe', 'Asia', 'Middle East']
Length: 4, dtype: str
-------------------------------
HAUL : <StringArray>
['LONG', 'SHORT']
Length: 2, dtype: str
-------------------------------
AIRCRAFT_TYPE : <StringArray>
['B777', 'A320', 'A350', 'B787', 'A380']
Length: 5, dtype: str
-------------------------------
FIRST_CLASS_SEATS : [ 8  0 14]
-------------------------------
BUSINESS_CLASS_SEATS : [49 17  8 13 20 56  4 10  2 48 12 18 42  5 15 97  3  9 11  1 32 31 16 14
  6  7 19 35  0]
-------------------------------
ECONOMY_SEATS : [178 163 172 167 160 275 176 170 200 168 162 166 175 165 358 177 171 224
 169 179 304 173 300 164 174 161 180]
-------------------------------
TIER1_ELIGIBLE_PAX : [ 0  1  2  4  3  5  6  8  7  9 20]
-------------------------------
TIER2_ELIGIBLE_PAX : [10  7 11 16  6 12  5  9  0  2  3  8  1  4 18 14 13 15 21 20 23 29 19 17
 25 22 24 26 27]
-------------------------------
TIER3_ELIGIBLE_PAX : [38 28 40 54 27 55 42 23 39 34  0  3 22 14 35 16  8 53 31 32 12 36 21 26
 59 30 43 11 10 33  7 19 47 24 20 46 45 17 25 13 51 29 18 37 60 69 48 52
 64 15  6  5 41 73 44  9 90 66  1 58 63 50 56 49  4 62 61 78 57  2 68 70
 71 65 80 72 79 67 76 77 92 75 81 74 85 83]
-------------------------------

In [14]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='North America') & (df['HAUL']=="LONG")]
filteredCategory.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
7,2025-04-24,14:50:00,Afternoon,BA,BA7116,LHR,ORD,USA,North America,LONG,A350,0,56,275,1,12,42
11,2025-09-02,07:48:00,Morning,BA,BA8942,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,5,23
16,2025-04-02,17:04:00,Afternoon,BA,BA8677,LHR,ORD,USA,North America,LONG,B787,8,42,166,0,2,14

In [29]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='North America') & (df['HAUL']=="LONG")]
totalSeats=filteredCategory['FIRST_CLASS_SEATS'].sum()+filteredCategory['BUSINESS_CLASS_SEATS'].sum()+filteredCategory['ECONOMY_SEATS'].sum()
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/totalSeats)*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/totalSeats)*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/totalSeats)*100
print(f"Total Seats: {totalSeats}\n Tier 1, 2 & 3: {tier1El}, {tier2El}, {tier3El}")

Total Seats: 776567
 Tier 1, 2 & 3: 1.324547656544767, 16.29080298287205, 82.38464936058318

In [32]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='Europe') & (df['HAUL']=="SHORT")]
totalSeats=filteredCategory['FIRST_CLASS_SEATS'].sum()+filteredCategory['BUSINESS_CLASS_SEATS'].sum()+filteredCategory['ECONOMY_SEATS'].sum()
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/totalSeats)*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/totalSeats)*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/totalSeats)*100
print(f"Total Seats: {totalSeats}\n Tier 1, 2 & 3: {tier1El}, {tier2El}, {tier3El}")

Total Seats: 1075500
 Tier 1, 2 & 3: 0.0, 5.571920037192004, 94.428079962808

In [38]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='Asia') & (df['HAUL']=="LONG")]
totalSeats=filteredCategory['FIRST_CLASS_SEATS'].sum()+filteredCategory['BUSINESS_CLASS_SEATS'].sum()+filteredCategory['ECONOMY_SEATS'].sum()
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/totalSeats)*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/totalSeats)*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/totalSeats)*100
print(f"Total Seats: {totalSeats}\n Tier 1, 2 & 3: {tier1El}, {tier2El}, {tier3El}")

Total Seats: 197355
 Tier 1, 2 & 3: 1.305262091155532, 16.248891591294875, 82.4458463175496

In [41]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='Middle East') & (df['HAUL']=="LONG")]
totalSeats=filteredCategory['FIRST_CLASS_SEATS'].sum()+filteredCategory['BUSINESS_CLASS_SEATS'].sum()+filteredCategory['ECONOMY_SEATS'].sum()
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/totalSeats)*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/totalSeats)*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/totalSeats)*100
print(f"Total Seats: {totalSeats}\n Tier 1, 2 & 3: {tier1El}, {tier2El}, {tier3El}")

Total Seats: 200647
 Tier 1, 2 & 3: 1.3007919380803101, 16.06552801686544, 82.63368004505425

[[Finding the representative samples ]]

In [46]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='North America') & (df['HAUL']=="LONG")].head(5)
totalSeats=[filteredCategory['FIRST_CLASS_SEATS'].sum(),filteredCategory['BUSINESS_CLASS_SEATS'].sum(),filteredCategory['ECONOMY_SEATS'].sum()]
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/sum(totalSeats))*100
print(f"{sum(totalSeats)}, {tier1El}, {totalSeats[0]}, {tier2El}, {totalSeats[1]}, {tier3El}, {totalSeats[2]}")

1252, 2.5559105431309903, 32, 19.568690095846645, 245, 77.87539936102237, 975

In [48]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='Europe') & (df['HAUL']=="SHORT")].head(5)
totalSeats=[filteredCategory['FIRST_CLASS_SEATS'].sum(),filteredCategory['BUSINESS_CLASS_SEATS'].sum(),filteredCategory['ECONOMY_SEATS'].sum()]
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/sum(totalSeats))*100
print(f"{sum(totalSeats)}, {tier1El}, {totalSeats[0]}, {tier2El}, {totalSeats[1]}, {tier3El}, {totalSeats[2]}")

900, 0.0, 0, 8.666666666666668, 78, 91.33333333333333, 822

In [50]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='Asia') & (df['HAUL']=="LONG")].head(5)
totalSeats=[filteredCategory['FIRST_CLASS_SEATS'].sum(),filteredCategory['BUSINESS_CLASS_SEATS'].sum(),filteredCategory['ECONOMY_SEATS'].sum()]
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/sum(totalSeats))*100
print(f"{sum(totalSeats)}, {tier1El}, {totalSeats[0]}, {tier2El}, {totalSeats[1]}, {tier3El}, {totalSeats[2]}")

1607, 1.3690105787181084, 22, 15.183571873055381, 244, 83.44741754822651, 1341

In [51]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='Middle East') & (df['HAUL']=="LONG")].head(5)
totalSeats=[filteredCategory['FIRST_CLASS_SEATS'].sum(),filteredCategory['BUSINESS_CLASS_SEATS'].sum(),filteredCategory['ECONOMY_SEATS'].sum()]
tier1El=(filteredCategory['FIRST_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier2El=(filteredCategory['BUSINESS_CLASS_SEATS'].sum()/sum(totalSeats))*100
tier3El=(filteredCategory['ECONOMY_SEATS'].sum()/sum(totalSeats))*100
print(f"{sum(totalSeats)}, {tier1El}, {totalSeats[0]}, {tier2El}, {totalSeats[1]}, {tier3El}, {totalSeats[2]}")

1238, 3.231017770597738, 40, 19.547657512116317, 242, 77.22132471728594, 956

[[ Grouping by flights ]]

In [52]:
filteredCategory =df[(df["ARRIVAL_REGION"]=='North America') & (df['HAUL']=="LONG")]

filteredCategory.head(5)

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
7,2025-04-24,14:50:00,Afternoon,BA,BA7116,LHR,ORD,USA,North America,LONG,A350,0,56,275,1,12,42
11,2025-09-02,07:48:00,Morning,BA,BA8942,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,5,23
16,2025-04-02,17:04:00,Afternoon,BA,BA8677,LHR,ORD,USA,North America,LONG,B787,8,42,166,0,2,14